### ISSUE TITLE
Infinite recursive calls in downloader class (v9.0.4)

### ISSUE THREAD

**Issue by Annih** [vrivellino/chef-java_se#3]
Hello,

With the latest version of `java_se`  (9.0.4) our code relying on it is not working anymore, hitting a stack too deep error:
```ruby
SystemStackError:    stack level too deep
     # /tmp/d20180411-7446-1f6rgce/cookbooks/java_se/libraries/downloader.rb:78:in `first_hash_argument'
     # /tmp/d20180411-7446-1f6rgce/cookbooks/java_se/libraries/downloader.rb:73:in `allow_redirections'
     # /tmp/d20180411-7446-1f6rgce/cookbooks/java_se/libraries/downloader.rb:60:in `open_uri'
```

**Comment by dhoer** [comment]
I don't see the 9 branch.  But if I had to guess, the path might of changed `9.0.4+11`? http://download.oracle.com/otn-pub/java/jdk/9.0.4+11/c2514751926b4512b076cc82f959763f/jdk-9.0.4_linux-x64_bin.tar.gz

**Comment by dhoer** [comment]
I forgot master was 9 and not 10. The link still looks good https://github.com/vrivellino/chef-java_se/blob/master/libraries/default.rb#L30-L31

**Comment by sulaimanismail** [comment]
I'm not able to download chef java_se 

22:51:01 Recipe: java_se::_windows_install
22:51:01 * ruby_block[fetch http://download.oracle.com/otn-pub/java/jdk/11.0.2+9/f51449fcd52f4d52b93a989c5c56ed3c/jdk-11.0.2_windows-x64_bin.exe] action run
22:52:02  
22:52:02 ================================================================================
22:52:02 Error executing action `run` on resource 'ruby_block[fetch http://download.oracle.com/otn-pub/java/jdk/11.0.2+9/f51449fcd52f4d52b93a989c5c56ed3c/jdk-11.0.2_windows-x64_bin.exe]'
22:52:02 ================================================================================
22:52:02  
22:52:02 ArgumentError
22:52:02 -------------
22:52:02 too many download failures from http://download.oracle.com/otn-pub/java/jdk/11.0.2+9/f51449fcd52f4d52b93a989c5c56ed3c/jdk-11.0.2_windows-x64_bin.exe
22:52:02  
22:52:02 Resource Declaration:
22:52:02 ---------------------
22:52:02 # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/java_se/libraries/default.rb
22:52:02  
22:52:02 52: ruby_block "fetch #{download_url}" do
22:52:02 53: block do
22:52:02 54: JavaSE::Downloader.fetch(download_url, file_cache_path, checksum)
22:52:02 55: end
22:52:02 56: not_if { ::File.exist?(file_cache_path) && JavaSE::Downloader.valid?(file_cache_path, checksum) }
22:52:02 57: end
22:52:02 58: end
22:52:02  
22:52:02 Compiled Resource:
22:52:02 ------------------
22:52:02 # Declared in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/java_se/libraries/default.rb:52:in `fetch_java_installer'
22:52:02  
22:52:02 ruby_block("fetch http://download.oracle.com/otn-pub/java/jdk/11.0.2+9/f51449fcd52f4d52b93a989c5c56ed3c/jdk-11.0.2_windows-x64_bin.exe") do
22:52:02 action [:run]
22:52:02 default_guard_interpreter :default
22:52:02 declared_type :ruby_block
22:52:02 cookbook_name "java_se"
22:52:02 recipe_name "_windows_install"
22:52:02 block #<Proc:0x000000000605c3e0@C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/java_se/libraries/default.rb:53>
22:52:02 block_name "fetch http://download.oracle.com/otn-pub/java/jdk/11.0.2+9/f51449fcd52f4d52b93a989c5c56ed3c/jdk-11.0.2_windows-x64_bin.exe"
22:52:02 not_if { #code block }
22:52:02 end
22:52:02  
22:52:02 System Info:
22:52:02 ------------
22:52:02 chef_version=14.0.202
22:52:02 platform=windows
22:52:02 platform_version=6.3.9600
22:52:02 ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
22:52:02 program_name=C:/opscode/chef/bin/chef-solo
22:52:02 executable=C:/opscode/chef/bin/chef-solo
22:52:02  
22:52:02  
22:52:02 Running handlers:
22:52:02 [2019-03-24T03:52:01+00:00] ERROR: Running exception handlers
22:52:02 [2019-03-24T03:52:01+00:00] ERROR: Running exception handlers
22:52:02 Running handlers complete
22:52:02 [2019-03-24T03:52:01+00:00] ERROR: Exception handlers complete
22:52:02 [2019-03-24T03:52:01+00:00] ERROR: Exception handlers complete
22:52:02 Chef Client failed. 1 resources updated in 01 minutes 21 seconds
22:52:02 [2019-03-24T03:52:01+00:00] FATAL: Stacktrace dumped to C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
22:52:02 [2019-03-24T03:52:01+00:00] FATAL: Stacktrace dumped to C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
22:52:02 [2019-03-24T03:52:01+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
22:52:02 [2019-03-24T03:52:01+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
22:52:02 [2019-03-24T03:52:01+00:00] FATAL: ArgumentError: ruby_block[fetch http://download.oracle.com/otn-pub/java/jdk/11.0.2+9/f51449fcd52f4d52b93a989c5c56ed3c/jdk-11.0.2_windows-x64_bin.exe] (java_se::_windows_install line 52) had an error: ArgumentError: too many download failures from http://download.oracle.com/otn-pub/java/jdk/11.0.2+9/f51449fcd52f4d52b93a989c5c56ed3c/jdk-11.0.2_windows-x64_bin.exe
22:52:02 [2019-03-24T03:52:01+00:00] FATAL: ArgumentError: ruby_block[fetch http://download.oracle.com/otn-pub/java/jdk/11.0.2+9/f51449fcd52f4d52b93a989c5c56ed3c/jdk-11.0.2_windows-x64_bin.exe] (java_se::_windows_install line 52) had an error: ArgumentError: too many download failures from http://download.oracle.com/otn-pub/java/jdk/11.0.2+9/f51449fcd52f4d52b93a989c5c56ed3c/jdk-11.0.2_windows-x64_bin.exe
22:52:02 >>>>>> ------Exception-------
22:52:02 >>>>>> Class: Kitchen::ActionFailed
22:52:02 >>>>>> Message: 1 actions failed.
22:52:02 >>>>>> Converge failed on instance <default-windows2012r2>. Please see .kitchen/logs/default-windows2012r2.log for more details
22:52:02 >>>>>> ----------------------
